# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c021a44a3b76283008e8569a96ba29a37ee26f1e710c1166b2de26830615584d85950b2259967a38e11b0a5dd7026da09fdd298b272aaf9f6da39be5b239b976

test:
  secret_key_base: a061013a5a5cd4787fae4937844a1d639bfd9846e5042b73ce28c96803680fed34274c728d511735abdeae57933803df14f8510c6df17eea9e1950b6cba58d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
